global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:9121"]

  - job_name: "rabbitmq"
    metrics_path: /metrics
    static_configs:
      - targets: ["rabbitmq:15672"]
      
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]
      
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
      
  - job_name: "fastify_app"
    static_configs:
      - targets: ["host.docker.internal:3000"]